### ISSUE TITLE
Convert to Nix

### ISSUE THREAD

**Issue by copumpkin** [thoughtpolice/haskell-donate#1]
WTF @thoughtpolice I thought you were a Nix person!

![disappoint](http://i1.kym-cdn.com/photos/images/newsfeed/000/003/866/nfNeT7YvTozx0cv7ze3mplZpo1_500.gif)

**Comment by thoughtpolice** [comment]
you sneaky lil' scoundrel.

**Comment by thoughtpolice** [comment]
Actually, in all seriousness, I _would_ do that... But we _really_ need to get Haskell.org more well oiled, and none of us just really have the time to work on NixOS enough to get the features we're looking into using (we're looking at Kubernetes, actually). Plus, if I get hit by a bus, Haskell.org won't exactly be very well off, then, since I'm the institutional Nixer there.

However, I can happily report I'm still using NixOS personally for my servers. And it works well enough to where I can swim along doing maintenance. So there's that! Therefore, I am closing this bug with status `ENOTWHATITSEEMS`. And with extreme prejudice.

**Comment by copumpkin** [comment]
😇

**Comment by thoughtpolice** [comment]
and in all seriousness though, `backend/Dockerfile` is a hilarious monstrosity
